# Generated by Django 4.2.16 on 2024-12-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_employerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
