# Generated by Django 4.2.16 on 2024-12-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_applicantprofile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='education',
        ),
    ]
