version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL="redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379"
      - DJANGO_SETTINGS_MODULE=server.settings

  celery:
    build: .
    command: celery -A server worker -l info
    volumes:
      - .:/app
    environment:
      - REDIS_URL="redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379"

  celery-beat:
    build: .
    command: celery -A server beat -l info
    volumes:
      - .:/app
    environment:
      - REDIS_URL="redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379"
