services:
  - type: web
    name: django-web-service
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    dockerCommand: >
      sh -c "celery -A server beat -l info & celery -A server worker -l info & python manage.py runserver 0.0.0.0:8000"
    branch: main
    healthCheckPath: /admin/login/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: django-web-service-mvlg.onrender.com
      - key: REDIS_URL
        value: redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379