services:
  # Django Web Service
  - type: web
    name: django-web-service
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    dockerCommand: python manage.py runserver 0.0.0.0:8000
    branch: main
    healthCheckPath: /admin/login/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-domain.onrender.com
      - key: REDIS_URL
        value: redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379

  # Celery Worker Service
  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: celery -A server worker -l info
    branch: main
    envVars:
      - key: REDIS_URL
        value: redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379

  # Celery Beat Service
  - type: worker
    name: celery-beat
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: celery -A server beat -l info
    branch: main
    envVars:
      - key: REDIS_URL
        value: redis://default:AV2QAAIjcDExNDJjNmRjOThkZmQ0NTRiYmM1MDg3NTkzYTk3ZjA5N3AxMA@huge-asp-23952.upstash.io:6379