# Generated by Django 4.2.16 on 2024-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
