# Generated by Django 4.2.16 on 2024-12-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profiles', '0003_applicantprofile_image'),
        ('employment_history', '0002_alter_employmenthistory_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_profiles.applicantprofile'),
        ),
    ]
