# Generated by Django 4.2.16 on 2024-12-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
