# Generated by Django 4.2.16 on 2024-12-04 09:04

import applicant_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profiles', '0002_alter_applicantprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=applicant_profiles.models.upload_to),
        ),
    ]
