# Generated by Django 4.2.16 on 2024-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
